# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k6vQ2Fi1fXo5jN7WR4FyyxxtAdI0SWmF
"""

import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
from scipy.stats import norm

# ==========================================================
# CONFIGURATION
# ==========================================================

CONFIG = {
    "ticker": "AAPL",
    "start_date": "2022-01-01",
    "end_date": "2023-12-31",
    "r": 0.03,
    "maturity_days": 30,
    "transaction_cost": 0.0005,
    "position_size": 1,
    "hedge_frequency": 1,
    "rolling_vol_window": 20,
    "gbm_mu": 0.08,
    "gbm_sigma": 0.25,
    "monte_carlo_paths": 1000
}

TRADING_DAYS = 252


# ==========================================================
# BLACK–SCHOLES FUNCTIONS
# ==========================================================

def bs_price(S, K, T, r, sigma):
    if T <= 0:
        return max(S - K, 0)
    d1 = (np.log(S/K) + (r + 0.5*sigma**2)*T)/(sigma*np.sqrt(T))
    d2 = d1 - sigma*np.sqrt(T)
    return S*norm.cdf(d1) - K*np.exp(-r*T)*norm.cdf(d2)


def bs_delta(S, K, T, r, sigma):
    if T <= 0:
        return 0
    d1 = (np.log(S/K) + (r + 0.5*sigma**2)*T)/(sigma*np.sqrt(T))
    return norm.cdf(d1)


# ==========================================================
# HISTORICAL DATA LOADER (FIXED)
# ==========================================================

def load_historical_data(config):

    df = yf.download(
        config["ticker"],
        start=config["start_date"],
        end=config["end_date"],
        auto_adjust=True  # Important fix
    )

    if "Close" not in df.columns:
        raise ValueError("Close column not found in downloaded data")

    df = df[["Close"]].rename(columns={"Close": "price"})
    df["log_ret"] = np.log(df["price"]).diff()

    df["vol"] = (
        df["log_ret"]
        .rolling(config["rolling_vol_window"])
        .std()
        * np.sqrt(TRADING_DAYS)
    )

    return df.dropna()


# ==========================================================
# GBM SIMULATION
# ==========================================================

def simulate_gbm(S0, mu, sigma, T_days, paths):

    dt = 1/TRADING_DAYS
    prices = np.zeros((T_days, paths))
    prices[0] = S0

    for t in range(1, T_days):
        z = np.random.normal(size=paths)
        prices[t] = prices[t-1] * np.exp(
            (mu - 0.5*sigma**2)*dt + sigma*np.sqrt(dt)*z
        )

    return prices


# ==========================================================
# DELTA HEDGING ENGINE
# ==========================================================

def delta_hedge_path(price_path, sigma, config):

    maturity = config["maturity_days"]
    r = config["r"]
    tc = config["transaction_cost"]
    position = config["position_size"]
    hedge_freq = config["hedge_frequency"]

    S0 = price_path[0]
    K = S0
    T0 = maturity/TRADING_DAYS

    option_price = bs_price(S0, K, T0, r, sigma)

    hedge_position = 0
    cash = option_price * position

    for t in range(len(price_path)):

        S = price_path[t]
        T = (maturity - t)/TRADING_DAYS

        delta = bs_delta(S, K, T, r, sigma) * position

        if t % hedge_freq == 0:
            hedge_change = -(delta - hedge_position)
            cost = abs(hedge_change) * S * tc
            cash -= hedge_change * S + cost
            hedge_position += hedge_change

        option_val = bs_price(S, K, T, r, sigma) * position

    final_value = cash + hedge_position*S - option_val
    return final_value


# ==========================================================
# HISTORICAL BACKTEST
# ==========================================================

def run_historical_backtest(data, config):

    pnl_results = []

    for i in range(len(data) - config["maturity_days"]):

        window = data.iloc[i:i+config["maturity_days"]]
        prices = window["price"].values
        sigma = window["vol"].iloc[0]

        pnl = delta_hedge_path(prices, sigma, config)
        pnl_results.append(pnl)

    return np.array(pnl_results)


# ==========================================================
# MONTE CARLO BACKTEST
# ==========================================================

def run_monte_carlo(config):

    S0 = 100

    prices = simulate_gbm(
        S0,
        config["gbm_mu"],
        config["gbm_sigma"],
        config["maturity_days"],
        config["monte_carlo_paths"]
    )

    hedging_errors = []

    for i in range(config["monte_carlo_paths"]):
        path = prices[:, i]
        pnl = delta_hedge_path(
            path,
            config["gbm_sigma"],
            config
        )
        hedging_errors.append(pnl)

    return np.array(hedging_errors)


# ==========================================================
# RISK METRICS
# ==========================================================

def risk_metrics(pnl_array):

    mean = np.mean(pnl_array)
    std = np.std(pnl_array)
    sharpe = mean/std if std != 0 else 0
    var_95 = np.percentile(pnl_array, 5)
    cvar_95 = pnl_array[pnl_array <= var_95].mean()

    return {
        "Mean PnL": mean,
        "Std Dev": std,
        "Sharpe": sharpe,
        "VaR 95%": var_95,
        "CVaR 95%": cvar_95
    }


# ==========================================================
# MAIN
# ==========================================================

if __name__ == "__main__":

    print("Running Historical Backtest...")
    hist_data = load_historical_data(CONFIG)
    hist_pnl = run_historical_backtest(hist_data, CONFIG)
    hist_stats = risk_metrics(hist_pnl)

    print("\nHistorical Stats:")
    for k, v in hist_stats.items():
        print(f"{k}: {v:.4f}")

    print("\nRunning GBM Monte Carlo Simulation...")
    mc_pnl = run_monte_carlo(CONFIG)
    mc_stats = risk_metrics(mc_pnl)

    print("\nMonte Carlo Stats:")
    for k, v in mc_stats.items():
        print(f"{k}: {v:.4f}")

    # Plot Monte Carlo distribution
    plt.figure(figsize=(10,5))
    plt.hist(mc_pnl, bins=50)
    plt.title("GBM Monte Carlo Hedging Error Distribution")
    plt.xlabel("PnL")
    plt.ylabel("Frequency")
    plt.show()

